### ISSUE TITLE
[bug]: Error at the end of the installation : Error at line: 1095 exiting with code 1 (last command was: fwconsole ma install sangomaconnect >> $log 2>&1)

### ISSUE THREAD

**Issue by fgadot** [FreePBX/sng_freepbx_debian_install#76] opened 2024-08-06 14:08 UTC
### FreePBX Version

FreePBX 17

### Issue Description

This is a brand new Debian 12x64, with updated packages. Absolutely nothing setup beside hostname.
FreePBX 17 Installations ends with an error:

2024-08-05 19:25:51 - Installing sangomaconnectmodule
2024-08-05 19:43:41 - Installation failed at step Installing sangomaconnectmodule. Please check log /var/log/pbx/freepbx17-install-2024.08.05-19.06.39.log for details.
2024-08-05 19:43:41 - Error at line: 1095 exiting with code 1 (last command was: fwconsole ma install sangomaconnect >> $log 2>&1)
2024-08-05 19:43:41 - Exiting script

### Operating Environment

Brand new Debian 12x64 (Digital Ocean).
Firewalls allows all TCP/UDP/ICMP out.

### Relevant log output

```shell
Log file ends with:


Configuration file '/etc/asterisk/statsd.conf'
 ==> File on system created by you or by a script.
 ==> File also in package provided by package maintainer.
 ==> Keeping old config file as default.
2024-08-05 19:25:37 - freepbx17 installed successfully....
2024-08-05 19:25:37 - ############################### 
2024-08-05 19:25:37 - Installing Sysadmin module
Updating tables sysadmin_options, sysadmin_update_log, sysadmin_fail2ban, sysadmin_expiry_notifications...Done
Sangoma PnP Server activated
Generating CSS...Done
Module sysadmin version 17.0.1.92 successfully installed
Updating Hooks...Done
Chowning directories...Done
2024-08-05 19:25:51 - Installing sangomaconnectmodule
Detected Missing Dependency of: restapps 17.0.1
Found local Dependency of: restapps 17.0.1.20
Detected Missing Dependency of: endpoint 17.0.1
Found local Dependency of: endpoint 17.0.1.73
Installing Missing Dependency of: endpoint 17.0.1
Create symlink...Done
Checking database tables...Done
Migrating tables as required...Done
Checking Settings and Defaults...Done
Generating Configs...Done
Downloading Firmware...Done (Background)
Enabling the DPMA...(Background) 
updating Logout phones config...(Background)Generating CSS...Done
Installed Missing Dependency of: endpoint 17.0.1
Installing Missing Dependency of: restapps 17.0.1
Updating tables restapps_settings, restapps_stats...Done
Stopping old running processes...Done
Generating CSS...Done
Installed Missing Dependency of: restapps 17.0.1
Updating tables sangomaconnect_user_pre_setup, sangomaconnect_user_setup, sangomaconnect_user_device, sangomaconnect_sngphone_sms_routing, sangomaconnect_phone_locations, sangomaconnect_account_phone_locations...Done
Increasing HTTP Session Limit
No PBXID file found, not registering module to cloud.
Checking module cloud activation status
System not activated, cannot perform cloud activation
Initializing node dependencies
Running installation..
npm WARN config only Use `--omit=dev` to omit dev dependencies from the install.
The process "runuser 'asterisk' -s '/bin/bash' -c 'cd /var/www/html/admin/modules/sangomaconnect/node && mkdir -p /home/asterisk/.pm2 && mkdir -p /var/www/html/admin/modules/sangomaconnect/node/logs && export HOME=/home/asterisk && export PM2_HOME=/home/asterisk/.pm2 && export ASTLOGDIR=/var/log/asterisk && export ASTVARLIBDIR=/var/lib/asterisk && export PATH=$HOME/.node/bin:$PATH && export NODE_PATH=$HOME/.node/lib/node_modules:$NODE_PATH && export MANPATH=$HOME/.node/share/man:$MANPATH && npm install --only=production'" exceeded the timeout of 600 seconds.
Failed updating libraries!

In Config.class.php line 890:
                                                                   
  SQLSTATE[HY000]: General error: 2006 MySQL server has gone away  
                                                                   

moduleadmin [-f|--force] [-d|--debug] [--edge] [--ignorecache] [--stable] [--color] [--skipchown] [-e|--autoenable] [--skipdisabled] [--snapshot SNAPSHOT] [--format FORMAT] [-R|--repo REPO] [-t|--tag TAG] [--skipbreakingcheck] [--sendemail] [--onlystdout] [--] [<args>...]

2024-08-05 19:43:41 - ****** INSTALLATION FAILED *****
2024-08-05 19:43:41 - Installation failed at step Installing sangomaconnectmodule. Please check log /var/log/pbx/freepbx17-install-2024.08.05-19.06.39.log for details.
2024-08-05 19:43:41 - Error at line: 1095 exiting with code 1 (last command was: fwconsole ma install sangomaconnect >> $log 2>&1)
2024-08-05 19:43:41 - Exiting script
```

**Comment by kguptasangoma** [comment] 2024-08-07 01:45
hey @fgadot looks like your DB either not stared or some issue happened with the mariadb ?
Please check the mariadb logs in `journalctl -u mariadb` if you find anything. 

Or try to execute "fwconsole m" to confirm if DB is working fine.

You can always re-run the installation script if DB is working fine.

**Comment by fgadot** [comment] 2024-08-07 16:34
@kguptasangoma 

It looks like MariaDB is working
root@fpbx00:~# mysqlshow 
+--------------------+
|     Databases      |
+--------------------+
| asterisk           |
| asteriskcdrdb      |
| information_schema |
| mysql              |
| performance_schema |
| sys                |
+--------------------+


root@fpbx00:~# fwconsole m
Reading table information for completion of table and column names
You can turn off this feature to get a quicker startup with -A

Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 49
Server version: 10.11.6-MariaDB-0+deb12u1 Debian 12

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [asterisk]> 


**Since FreePBX is not releasing ISO anymore, this is simulating a brand new installation. 
Out of the box Debian. Update. Then run the install script. 
Please make correct adjustment in the installation script so a new installation does NOT display errors or a message that it failed.** 

root@fpbx00:~# 
root@fpbx00:~# journalctl -u mariadb
Aug 05 19:10:06 fpbx00 systemd[1]: Starting mariadb.service - MariaDB 10.11.6 database server...
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] Starting MariaDB 10.11.6-MariaDB-0+deb12u1 source revision  as process 11079
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] InnoDB: Compressed tables use zlib 1.2.13
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] InnoDB: Number of transaction pools: 1
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] InnoDB: Using liburing
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] InnoDB: Completed initialization of buffer pool
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] InnoDB: End of log at LSN=46980
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] InnoDB: 128 rollback segments are active.
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] InnoDB: log sequence number 46980; transaction id 14
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] Plugin 'FEEDBACK' is disabled.
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] Server socket created on IP: '127.0.0.1'.
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] InnoDB: Buffer pool(s) load completed at 240805 19:10:06
Aug 05 19:10:06 fpbx00 mariadbd[11079]: 2024-08-05 19:10:06 0 [Note] /usr/sbin/mariadbd: ready for connections.
Aug 05 19:10:06 fpbx00 mariadbd[11079]: Version: '10.11.6-MariaDB-0+deb12u1'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Debian 12
Aug 05 19:10:07 fpbx00 systemd[1]: Started mariadb.service - MariaDB 10.11.6 database server.
Aug 05 19:10:07 fpbx00 /etc/mysql/debian-start[11094]: Upgrading MySQL tables if necessary.
Aug 05 19:10:07 fpbx00 /etc/mysql/debian-start[11105]: Checking for insecure root accounts.
Aug 05 19:10:07 fpbx00 /etc/mysql/debian-start[11109]: Triggering myisam-recover for all MyISAM tables and aria-recover for all Aria tables
Aug 05 19:23:25 fpbx00 mariadbd[11079]: 2024-08-05 19:23:25 42 [Warning] Access denied for user 'freepbxuser'@'localhost' (using password: YES)
Aug 05 19:23:25 fpbx00 mariadbd[11079]: 2024-08-05 19:23:25 43 [Warning] Access denied for user 'freepbxuser'@'localhost' (using password: YES)
Aug 05 19:23:27 fpbx00 mariadbd[11079]: 2024-08-05 19:23:27 47 [Warning] Access denied for user 'freepbxuser'@'localhost' (using password: YES)
Aug 05 19:24:37 fpbx00 mariadbd[11079]: 2024-08-05 19:24:37 0 [Note] /usr/sbin/mariadbd (initiated by: root[root] @ localhost []): Normal shutdown
Aug 05 19:24:37 fpbx00 mariadbd[11079]: 2024-08-05 19:24:37 0 [Note] InnoDB: FTS optimize thread exiting.
Aug 05 19:24:37 fpbx00 mariadbd[11079]: 2024-08-05 19:24:37 0 [Note] InnoDB: Starting shutdown...
Aug 05 19:24:37 fpbx00 mariadbd[11079]: 2024-08-05 19:24:37 0 [Note] InnoDB: Dumping buffer pool(s) to /var/lib/mysql/ib_buffer_pool
Aug 05 19:24:37 fpbx00 mariadbd[11079]: 2024-08-05 19:24:37 0 [Note] InnoDB: Buffer pool(s) dump completed at 240805 19:24:37
Aug 05 19:24:38 fpbx00 mariadbd[11079]: 2024-08-05 19:24:38 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
Aug 05 19:24:38 fpbx00 mariadbd[11079]: 2024-08-05 19:24:38 0 [Note] InnoDB: Shutdown completed; log sequence number 2656869; transaction id 1422
Aug 05 19:24:38 fpbx00 mariadbd[11079]: 2024-08-05 19:24:38 0 [Note] /usr/sbin/mariadbd: Shutdown complete
Aug 05 19:24:38 fpbx00 systemd[1]: mariadb.service: Deactivated successfully.
Aug 05 19:24:38 fpbx00 systemd[1]: mariadb.service: Consumed 3.788s CPU time.
Aug 05 19:24:42 fpbx00 systemd[1]: Starting mariadb.service - MariaDB 10.11.6 database server...
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] Starting MariaDB 10.11.6-MariaDB-0+deb12u1 source revision  as process 110393
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] InnoDB: Compressed tables use zlib 1.2.13
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] InnoDB: Number of transaction pools: 1
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] InnoDB: Using liburing
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] InnoDB: Completed initialization of buffer pool
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] InnoDB: End of log at LSN=2656869
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] InnoDB: 128 rollback segments are active.
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] InnoDB: log sequence number 2656869; transaction id 1423
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] Plugin 'FEEDBACK' is disabled.
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] Server socket created on IP: '127.0.0.1'.
Aug 05 19:24:42 fpbx00 mariadbd[110393]: 2024-08-05 19:24:42 0 [Note] /usr/sbin/mariadbd: ready for connections.
Aug 05 19:24:42 fpbx00 mariadbd[110393]: Version: '10.11.6-MariaDB-0+deb12u1'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Debian 12
Aug 05 19:24:42 fpbx00 systemd[1]: Started mariadb.service - MariaDB 10.11.6 database server.
Aug 05 19:24:43 fpbx00 /etc/mysql/debian-start[110415]: Upgrading MySQL tables if necessary.
Aug 05 19:24:43 fpbx00 /etc/mysql/debian-start[110429]: Checking for insecure root accounts.
Aug 05 19:24:43 fpbx00 /etc/mysql/debian-start[110433]: Triggering myisam-recover for all MyISAM tables and aria-recover for all Aria tables
Aug 05 19:24:43 fpbx00 mariadbd[110393]: 2024-08-05 19:24:43 0 [Note] InnoDB: Buffer pool(s) load completed at 240805 19:24:43
Aug 05 19:26:10 fpbx00 mariadbd[110393]: 2024-08-05 19:26:10 40 [Warning] Aborted connection 40 to db: 'asteriskcdrdb' user: 'freepbxuser' host: 'localhost' (Got an error reading communication packets)
Aug 05 19:26:10 fpbx00 mariadbd[110393]: 2024-08-05 19:26:10 44 [Warning] Aborted connection 44 to db: 'asterisk' user: 'freepbxuser' host: 'localhost' (Got an error reading communication packets)
Aug 05 19:26:19 fpbx00 mariadbd[110393]: 2024-08-05 19:26:19 65 [Warning] Aborted connection 65 to db: 'asterisk' user: 'freepbxuser' host: 'localhost' (Got an error reading communication packets)
-- Boot 043be291197f4956833ec0031e1baa70 --
Aug 07 16:29:24 fpbx00 systemd[1]: Starting mariadb.service - MariaDB 10.11.6 database server...
Aug 07 16:29:27 fpbx00 mariadbd[659]: 2024-08-07 16:29:27 0 [Note] Starting MariaDB 10.11.6-MariaDB-0+deb12u1 source revision  as process 659
Aug 07 16:29:27 fpbx00 mariadbd[659]: 2024-08-07 16:29:27 0 [Note] InnoDB: Compressed tables use zlib 1.2.13
Aug 07 16:29:27 fpbx00 mariadbd[659]: 2024-08-07 16:29:27 0 [Note] InnoDB: Number of transaction pools: 1
Aug 07 16:29:27 fpbx00 mariadbd[659]: 2024-08-07 16:29:27 0 [Note] InnoDB: Using crc32 + pclmulqdq instructions
Aug 07 16:29:27 fpbx00 mariadbd[659]: 2024-08-07 16:29:27 0 [Note] InnoDB: Using liburing
Aug 07 16:29:27 fpbx00 mariadbd[659]: 2024-08-07 16:29:27 0 [Note] InnoDB: Initializing buffer pool, total size = 128.000MiB, chunk size = 2.000MiB
Aug 07 16:29:28 fpbx00 mariadbd[659]: 2024-08-07 16:29:28 0 [Note] InnoDB: Completed initialization of buffer pool
Aug 07 16:29:28 fpbx00 mariadbd[659]: 2024-08-07 16:29:28 0 [Note] InnoDB: File system buffers for log disabled (block size=512 bytes)
Aug 07 16:29:28 fpbx00 mariadbd[659]: 2024-08-07 16:29:28 0 [Note] InnoDB: Starting crash recovery from checkpoint LSN=2656853
Aug 07 16:29:29 fpbx00 mariadbd[659]: 2024-08-07 16:29:29 0 [Note] InnoDB: End of log at LSN=13768651
Aug 07 16:29:29 fpbx00 mariadbd[659]: 2024-08-07 16:29:29 0 [Note] InnoDB: To recover: 897 pages
Aug 07 16:29:29 fpbx00 mariadbd[659]: 2024-08-07 16:29:29 0 [Note] InnoDB: 128 rollback segments are active.
Aug 07 16:29:29 fpbx00 mariadbd[659]: 2024-08-07 16:29:29 0 [Note] InnoDB: Removed temporary tablespace data file: "./ibtmp1"
Aug 07 16:29:29 fpbx00 mariadbd[659]: 2024-08-07 16:29:29 0 [Note] InnoDB: Setting file './ibtmp1' size to 12.000MiB. Physically writing the file full; Please wait ...
Aug 07 16:29:29 fpbx00 mariadbd[659]: 2024-08-07 16:29:29 0 [Note] InnoDB: File './ibtmp1' size is now 12.000MiB.
Aug 07 16:29:29 fpbx00 mariadbd[659]: 2024-08-07 16:29:29 0 [Note] InnoDB: log sequence number 13768651; transaction id 2699
Aug 07 16:29:29 fpbx00 mariadbd[659]: 2024-08-07 16:29:29 0 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
Aug 07 16:29:29 fpbx00 mariadbd[659]: 2024-08-07 16:29:29 0 [Note] Plugin 'FEEDBACK' is disabled.
Aug 07 16:29:29 fpbx00 mariadbd[659]: 2024-08-07 16:29:29 0 [Warning] You need to use --log-bin to make --expire-logs-days or --binlog-expire-logs-seconds work.
Aug 07 16:29:29 fpbx00 mariadbd[659]: 2024-08-07 16:29:29 0 [Note] Server socket created on IP: '127.0.0.1'.
Aug 07 16:29:30 fpbx00 mariadbd[659]: 2024-08-07 16:29:30 0 [Note] /usr/sbin/mariadbd: ready for connections.
Aug 07 16:29:30 fpbx00 mariadbd[659]: Version: '10.11.6-MariaDB-0+deb12u1'  socket: '/run/mysqld/mysqld.sock'  port: 3306  Debian 12
Aug 07 16:29:30 fpbx00 mariadbd[659]: 2024-08-07 16:29:30 0 [Note] InnoDB: Buffer pool(s) load completed at 240807 16:29:30
Aug 07 16:29:32 fpbx00 systemd[1]: Started mariadb.service - MariaDB 10.11.6 database server.
Aug 07 16:29:32 fpbx00 /etc/mysql/debian-start[1065]: Upgrading MySQL tables if necessary.
Aug 07 16:29:32 fpbx00 /etc/mysql/debian-start[1109]: Checking for insecure root accounts.
Aug 07 16:29:32 fpbx00 /etc/mysql/debian-start[1123]: Triggering myisam-recover for all MyISAM tables and aria-recover for all Aria tables

**Comment by fgadot** [comment] 2024-08-13 13:13
@kguptasangoma I can reproduce the issue on a new install. 
It looks like it s installed at the end. I dont know about "correctly".

**Comment by fgadot** [comment] 2024-08-13 16:44
@kguptasangoma actually I spoke too fast. 

First login to console (root) shows this:
Linux fpbx00 6.1.0-22-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.94-1 (2024-06-21) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Exception: SQLSTATE[HY000] [2002] Connection refused::SQLSTATE[HY000] [2002] Connection refused in file /var/www/html/admin/libraries/utility.functions.php on line 120

Caused by
PDOException: SQLSTATE[HY000] [2002] Connection refused in file /var/www/html/admin/libraries/BMO/Database.class.php on line 141
Stack trace:
  1. Exception->() /var/www/html/admin/libraries/utility.functions.php:120
  2. die_freepbx() /var/www/html/admin/libraries/BMO/Database.class.php:147
  3. PDOException->() /var/www/html/admin/libraries/BMO/Database.class.php:141
  4. PDO->__construct() /var/www/html/admin/libraries/BMO/Database.class.php:141
  5. FreePBX\Database->__construct() /var/www/html/admin/libraries/BMO/FreePBX.class.php:83
  6. FreePBX->__construct() /var/www/html/admin/bootstrap.php:144
  7. require_once() /etc/freepbx.conf:12
  8. include_once() /var/lib/asterisk/bin/fwconsole:12


While FreePBX 16 installs does not do that. 
After reboot, I can connect,

Linux fpbx00 6.1.0-22-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.94-1 (2024-06-21) x86_64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Tue Aug 13 16:29:00 2024 from 47.205.47.110
______                   ______ ______ __   __
|  ___|                  | ___ \| ___ \\ \ / /
| |_    _ __   ___   ___ | |_/ /| |_/ / \ V / 
|  _|  | '__| / _ \ / _ \|  __/ | ___ \ /   \ 
| |    | |   |  __/|  __/| |    | |_/ // /^\ \
\_|    |_|    \___| \___|\_|    \____/ \/   \/
                                              
                                              
NOTICE! You have 7 notifications! Please log into the UI to see them!
Current Network Configuration
+-----------+-------------------+---------------------------+
| Interface | MAC Address       | IP Addresses              |
+-----------+-------------------+---------------------------+
| eth0      | xxx | aaaaa             |
| eth1      | xxxx | 192.168.200.3             |
+-----------+-------------------+---------------------------+

Please note most tasks should be handled through the GUI.
You can access the GUI by typing one of the above IPs in to your web browser.
For support please visit: 
    http://www.freepbx.org/support-and-professional-services

+---------------------------------------------------------------------+
| This machine is not activated.  Activating your system ensures that |
| your machine is eligible for support and that it has the ability to |
| install Commercial Modules.                                         |
|                                                                     |
| If you already have a Deployment ID for this machine, simply run:   |
|                                                                     |
|    fwconsole sysadmin activate deploymentid                         |
|                                                                     |
| to assign that Deployment ID to this system. If this system is new, |
| please go to Activation (which is on the System Admin page in the   |
| Web UI) and create a new Deployment there.                          |
+---------------------------------------------------------------------+

root@fpbx00:~# 


I can connect using the IP address from interface eth0 (public IP Address). 
But I end up on the default Apache2 Debian page. 

/etc/apache2/sites-enabled only has 000-default.conf

**Comment by kguptasangoma** [comment] 2024-08-13 16:50
hi @fgadot problem is installation script got failed in half way through due to your DB error.

question is why it failed to connect to the DB and all of sudden it worked fine after installation.

did you modified or fixed anything to connect to the db ?

**Comment by fgadot** [comment] 2024-08-13 19:30
@kguptasangoma 
I was able to reproduce this issue multiple time with Digital Ocean Debian 12 droplet. 
I took a Debian 12 NetInstall in my lab, and no issue. 
Let's close this ticket. Thanks

**Comment by kguptasangoma** [comment] 2024-08-14 03:48
We have tested in digital ocean also and its fine for us. Closing as not reproducible. thanks

**Closed by kguptasangoma** 2024-08-14 03:48 UTC
Labels: bug, triage, installer

**Comment by peymil** [comment] 2024-08-22 10:21
I'm still having the same issue in 1vcpu 1gb debian 12x64 digitalocean server. I didn't modify anything and directly ran the installation script. Tried to debug it but no luck. If someone wants to check it I can provide you the ssh key and server ip. Just send me an email address.

**Comment by msanthosh18** [comment] 2024-08-22 10:31
Hi @peymil 
Can you send the system login access to **msanthosh@sangoma.com**
so that we can take look.

**Comment by peymil** [comment] 2024-08-22 10:36
Sent

**Comment by msanthosh18** [comment] 2024-08-22 10:59
Thanks we will check further

**Comment by msanthosh18** [comment] 2024-08-26 09:14
The system is going out of memory which cased the mysql service down while installing the modules, i would suggest to  increase the RAM to avoid such issues.

syslong;

`grep -i "Killed process" /var/log/syslog-20240825
2024-08-22T10:11:14.096218+00:00 debian-s-1vcpu-1gb-fra1-01 kernel: [ 1621.719374] Out of memory: Killed process 110362 (mariadbd) total-vm:1097988kB, anon-rss:270940kB, file-rss:0kB, shmem-rss:0kB, UID:107 pgtables:724kB oom_score_adj:0
2024-08-23T17:19:41.493175+00:00 debian-s-1vcpu-1gb-fra1-01 kernel: [113727.616394] Out of memory: Killed process 566917 (php) total-vm:559764kB, anon-rss:275696kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:768kB oom_score_adj:0
2024-08-23T17:21:31.604222+00:00 debian-s-1vcpu-1gb-fra1-01 kernel: [113837.797440] Out of memory: Killed process 567638 (php) total-vm:534832kB, anon-rss:272592kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:764kB oom_score_adj:0
2024-08-23T17:21:54.129133+00:00 debian-s-1vcpu-1gb-fra1-01 kernel: [113860.173068] Out of memory: Killed process 567654 (php) total-vm:534832kB, anon-rss:272488kB, file-rss:0kB, shmem-rss:0kB, UID:0 pgtables:764kB oom_score_adj:0
2024-08-23T17:40:58.353495+00:00 debian-s-1vcpu-1gb-fra1-01 kernel: [115004.523889] Out of memory: Killed process 561391 (mariadbd) total-vm:1098264kB, anon-rss:267616kB, file-rss:0kB, shmem-rss:0kB, UID:107 pgtables:780kB oom_score_adj:0
root@debian-s-1vcpu-1gb-fra1-01:~#
`
